# Site settings
title:            Team Dust
description:      "Minimal Jekyll theme for storytellers"
baseurl:          ""
url:              "https://teamdust.github.io"

# Author
author:
  name:           oh-really
  url:            "https://teamdust.github.io"
  email:          teamdust0219@gmail.com

# Build settings
markdown:         kramdown
disqus-shortname: teamdust

# Assets
sass:
  sass_dir:       _sass
  style:          compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:        /:year-:month-:day/:title
paginate:         5
